import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={(inter.className, 'px-4')}>
        <Image
          src='/logo.avif'
          alt='Weather Query'
          width={40}
          height={40}
          className='fixed left-4 top-4 rounded-lg sm:left-10'
          priority={true}
        />
        {children}
      </body>
    </html>
  )
}
